language: objective-c
os: osx
osx_image: xcode11

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=SwipeTransition.xcodeproj
    - CONFIG=Release
    - ACTION="build-for-testing test-without-building"

branches:
  only: 
    - master

cache:
  directories:
    - Carthage

matrix:
  include:
    - env: JOB=pod_lint
      script:
        - pod lib lint --quick
    - env: JOB=danger
      script:
        - bundle install --path vendor/bundle
        - bundle exec danger --verbose
    - env: JOB=xcode SCHEME=SwipeTransition SDK=iphonesimulator

script:
  - set -o pipefail
  - xcodebuild $ACTION -project $PROJECT -scheme $SCHEME -sdk $SDK -destination 'name=iPhone 11,OS=13.0' -configuration $CONFIG ENABLE_TESTABILITY=YES | xcpretty

notifications:
  email: false

after_success:
- |
  if [ "$JOB" == "xcode" ]; then
    bash <(curl -s https://codecov.io/bash)
  fi
  sleep 5 # workaround https://github.com/travis-ci/travis-ci/issues/4725

